export const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      img: "/images/vintage6.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      desc: "high quality product",
    },
    {
      _id: 2,
      name: "Adidas Fit Shirt",
      category: "Shirts",
      img: "/images/vintage4.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      desc: "high quality product",
    },
    {
      _id: 3,
      name: "Lacoste Free Shirt",
      category: "Shirts",
      img: "/images/vintage1.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 17,
      desc: "high quality product",
    },
    {
      _id: 4,
      name: "Nike Slim Pant",
      category: "Pants",
      img: "/images/vintage1.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      desc: "high quality product",
    },
    {
      _id: 5,
      name: "Puma Slim Pant",
      category: "Pants",
      img: "/images/vintage2.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      desc: "high quality product",
    },

    {
      _id: 6,
      name: "Adidas Fit Pant",
      category: "Pants",
      img: "/images/vintage7.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      desc: "high quality product",
    },
  ],
};
